[package]
name = "kernel_limine"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
limine = "0.2.0"
uefi = "0.28.0"
x86_64 = "0.15.1"
xmas-elf = "0.9.1"
