[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.kernel]
command = "cargo"
args = ["b", "--target", "i686-unknown-linux-gnu", "--package", "kernel", "--release"]
dependencies = ["format"]

[tasks.biboot]
command = "cargo"
args = ["b", "--target", "i686-unknown-uefi", "--package", "biboot", "--release"]
dependencies = ["format"]

[tasks.full]
dependencies = ["format", "kernel", "biboot"]

[tasks.boot]
script = [
	"cp ../target/i686-unknown-uefi/release/biboot.efi ../boot/efi/boot/BOOTIA32.efi",
	"cp ../target/i686-unknown-linux-gnu/release/kernel ../boot/kernel"
]
dependencies = ["full"]

[tasks.qemu]
script = [
	"qemu-system-x86_64 -enable-kvm -drive if=pflash,format=raw,readonly=on,file=../OVMF_CODE.fd -drive if=pflash,format=raw,readonly=on,file=../OVMF_VARS.fd -drive format=raw,file=fat:rw:../boot"
]
dependencies = ["boot"]

[tasks.format]
command = "cargo"
args = ["fmt"]

[tasks.clean]
command = "cargo"
args = ["clean"]
